import type { Metadata } from "next";
import { MantineProvider} from '@mantine/core';
import '@mantine/core/styles.css';
import { FooterCentered } from "@/components/Footer/FooterCentered";
import { ToastContainer } from 'react-toastify';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-screen h-full flex flex-col">
          <MantineProvider>
            <div className="flex flex-col flex-1">
              <div className="flex-1">
                {children}
                <ToastContainer position="top-right" autoClose={1000} />
              </div>
              <FooterCentered />
            </div>
          </MantineProvider>
      </body>
    </html>
  );
}
